site_name: 'Fab Lab Siegen'
repo_url: 'https://github.com/FabLabSiegen/fabdocs'
repo_name: 'fablabsiegen:fabdocs'
edit_uri: edit/master/docs/
site_author: 'Fab Lab Siegen'

pages:
    - Fab Lab Siegen:
      - Ziele und Aufgaben: 'index.md'
      - Community: 'about/community.md'
      - Team und Zuständigkeiten: 'about/team.md'
      - Chronik: 'about/org.md'
      - Zusammenarbeit: 'about/org.md'

    - 'Blog': 'index.md'

    - 'Galerie': 'index.md'


    - Infrastruktur:
#      - Overview: 'infrastructure/index.md'
      - Räume und Orte: 'infrastructure/Raum.md'
      - Laser Cutter: 'infrastructure/Laser-Cutter.md'
      - CNC-Fräsen:
        - X-Carve: 'infrastructure/CNC-Fraese_X-Carve.md'
        - Portalfräse EAS: 'infrastructure/CNC-Portalfraese_Heavy.md'
        - Stämpfli: 'infrastructure/Staempfli.md'
      - 3D-Druck:
        - 'infrastructure/3D-Druck/Ultimaker.md'
        - 'infrastructure/3D-Druck/PrintrBot.md'
        - 'infrastructure/3D-Druck/Form1.md'
        - 'infrastructure/3D-Druck/LulzBotTAZ5.md'
        - 'infrastructure/3D-Druck/MarkOne.md'
        - 'infrastructure/3D-Druck/MarkTwo.md'
        - 'infrastructure/3D-Druck/Replicator2X.md'
        - 'infrastructure/3D-Druck/ReplicatorDual.md'
        - 'infrastructure/3D-Druck/Aya.md'
      - Hand- und Elektrowerkzeuge: 'infrastructure/Elektrowerkzeug.md'
      - Stoff und Nähen: 'infrastructure/Laser-Cutter.md'
      - Elektrowerkstatt: 'infrastructure/Elektronik-Bereich.md'
      - Lager und Material: 'infrastructure/Lager.md'
      - Sonstiges: 'infrastructure/Computer.md'

    - Sicherheit und Regeln:
      - The Rules in a Nutshell: 'learn-share/community-safety.md'
      - Sicherheitseinweisungen: 'briefings-rules/Grundregeln/index.md'
      - Laborordnung: 'briefings-rules/Laborordnung.md'
      # - Unterweisung Laser: 'briefings-rules/Einweisung_Laser/index.md'
      # - Unterweisung 3D-Drucker: 'briefings-rules/Einweisung_3D-Drucker/index.md'
      # - Unterweisung E-Werkstatt: 'briefings-rules/Einweisung_E-Werkstatt/index.md'
      # - Unterweisung Elektrowerkzeug: 'briefings-rules/Einweisung_Elektro-Werkzeuge/index.md'
      - Raumnutzung & Aufsicht: 'briefings-rules/Laborordnung.md'
      # - Unterweisung Fräsen: 'briefings-rules/Einweisung_Fraese/index.md'


    - 'Lernen im Lab':
      - 'Offenes Labor / Open Lab': 'workwithus/openlabs.md'
      - 'Wissen Teilen / Sharing Knowledge': 'learn-share/how-to-docs.md'
      - Semester Courses:
        - 'FAB101 lecture': 'learn-share/fab-basics.md'
        - 'Seminar: Reading Class': 'learn-share/how-to-docs.md'
        - 'Seminar: Open Lab': 'learn-share/how-to-docs.md'
        - 'Seminar: LabLab': 'learn-share/how-to-docs.md'
        - 'Seminar: IoT': 'learn-share/how-to-docs.md'
        - 'Seminar: 3D printing': 'learn-share/how-to-docs.md'
        - 'Seminar: Produktentwicklung III': 'learn-share/how-to-docs.md'
        - 'Seminar: Labor Additive Fertigung': 'learn-share/how-to-docs.md'
      - 'Open Topics for Students': 'workwithus/qualification.md'
      - MINT:Lab Siegen: 'learn-share/how-to-docs.md'
      - VDI Zukunftspiloten Siegen: 'learn-share/how-to-docs.md'
      - 'Workshops': 'workwithus/openlabs.md'
  #    - 'Arduino in a Nutshell': 'learn-share/how-to-docs.md'
      - 'Other learning resources': 'learn-share/how-to-docs.md'

    - Projekte:
      - Übersicht / Overview: 'projects.md'
      - FAB101: 'projects.md'
      - ZEIT.RAUM: 'projects.md'
      - YALLAH: 'projects.md'
      - Access Control: 'projects.md'
      - Hush-Box: 'projects/Hush-Box.md'
      - Aya: 'projects/Aya.md'
      - Lab-Status: 'projects/Lab-Status.md'
      - Gamebly: 'projects/Gamebly.md'
      - Mobile & Temporary Labs: 'projects.md'
      - 3D-Druck mit Faserverbund-Werkstoffen: 'projects.md'
      - Sonstige Projekte und Ideen: 'projects.md'

 #     - FAB101
 #     - ZEIT.RAUM Siegen
 #     - Siegen Unter Tage
 #     - Open Labs & Education (Open Lab, Student Lab, Mobile Labs, HCI Lab, 3D Café, Zukunftspiloten, Holospace, ...)
 #     - YALLAH
 #     - Lab Projects
 #     - (Student) Research


    - 'Events': 'events.md'
#     - 'Conferences': 'events/conferences.md'
#      - 'Open Lab Days': 'workwithus/openlabs.md'
#     - 'Workshops & Talks':
#     - (Mobile) Makerspaces



    - 'Kontakt':
      - 'Adresse': 'workwithus/events.md'
      - 'Öffnungszeiten': 'workwithus/openlabs.md'
      - 'Soziale und andere Medien': 'workwithus/events.md'
      - 'Ansprechpersonen': 'about/team.md'



markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
  - footnotes

theme:
  name: material
  custom_dir: 'theme/material'

extra_css:
    - css/footer.css

extra:
  logo: 'images/logo.png'
  palette:
    primary: 'grey'
    accent: 'amber'
  font:
    text: 'Open Sans'
    code: 'Inconsolata'
#  social:
#    - type: 'twitter'
#      link: 'https://twitter.com/fablabsiegen'
#    - type: 'facebook'
#      link: 'http://facebook.com/fablabsiegen'
