site_name: 'SGN.LAB'
repo_url: 'https://github.com/FabLabSiegen/fabdocs'
repo_name: 'fablabsiegen:fabdocs'
edit_uri: edit/master/docs/
site_favicon: 'images/favicon-32x32.png'

pages:
    - About:
      - Mission: 'index.md'   
      - Community: 'about/community.md'
      - Spaces: 'about/space.md'
      - Team: 'about/space.md'            
      - Organization: 'about/org.md'
#      - Timeline: 'about/timeline.md'
    - The Lab: 
      - SGN.LAB: 'lab/sgnlab.md'    
      - Fab Lab: 'lab/fablab.md'
 #     - HCI Lab: 'lab/hcilab.md'
      - Holospace: 'lab/holospace.md'
      - Mobile Lab: 'lab/mobile.md' 
 #     - 3D Café: 'lab/3dcafe.md'                 
    - Projects: 'projects.md'
 #     - Workshops, Talks & Mobile Makerspaces
 #     - FAB101
 #     - ZEIT.RAUM Siegen
 #     - Siegen Unter Tage
 #     - Open Labs & Education (Open Lab, Student Lab, Mobile Labs, HCI Lab, 3D Café, Zukunftspiloten, Holospace, ...) 
 #     - YALLAH
 #     - Lab Projects 
 #     - (Student) Research      
    - Learn & Share: 
      - Community & Safety: 'learn-share/community-safety.md' 
      - 'How to: Documentation': 'learn-share/how-to-docs.md'   
      - Fab Basics: 'learn-share/fab-basics.md'
#      - 'Seminar: Reading Class': 'learn-share/rc.md'
#      - 'Seminar: Open Lab': 'learn-share/openlab-seminar.md'
#      - 'Seminar: LabLab': 'learn-share/lablab.md'
#      - 'Seminar: IoT': 'learn-share/iot.md'
#      - 'Seminar: 3D printing': 'learn-share/3dp.md'
#      - 'Seminar: Produktentwicklung III': 'learn-share/pe3.md'
#      - 'Other learning resources': 'learn-share/other.md'
#      - 'Events': 'events/events.md'
#      - 'Conferences': 'events/conferences.md'      
    - Work with us:
      - 'Open Lab Days': 'workwithus/openlabs.md'
      - 'Research': 'workwithus/research.md'
      - 'Consulting': 'workwithus/consulting.md'
      - 'Events': 'workwithus/events.md'
      - 'Qualification': 'workwithus/qualification.md'
    - Imprint: 'imprint.md'


markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
  - footnotes

theme_dir: 'theme/material'
#theme: 'material'

extra_css:
    - css/footer.css
    
    
extra:
  logo: 'images/logo.png'
  palette:
    primary: 'grey'
    accent: 'amber'
  font:
    text: 'Open Sans'
    code: 'Inconsolata'
#  social:
#    - type: 'twitter'
#      link: 'https://twitter.com/fablabsiegen'
#    - type: 'facebook'
#      link: 'http://facebook.com/fablabsiegen'
