site_name: 'SGN.LAB'
repo_url: 'https://github.com/FabLabSiegen/fabdocs'
repo_name: 'fablabsiegen:fabdocs'
edit_uri: edit/master/docs/
site_author: 'Fab Lab Siegen'

pages:
    - About:
      - Mission: 'index.md'
      - Community: 'about/community.md'
      - Spaces: 'about/space.md'
      - Team: 'about/space.md'
      - Organization: 'about/org.md'
#      - Timeline: 'about/timeline.md'
    - The Lab:
      - SGN.LAB: 'lab/sgnlab.md'
      - Fab Lab: 'lab/fablab.md'
 #     - HCI Lab: 'lab/hcilab.md'
      - Holospace: 'lab/holospace.md'
      - Mobile Lab: 'lab/mobile.md'
 #     - 3D Café: 'lab/3dcafe.md'

    - Briefings & Rules:
      - Laborordnung: 'briefings-rules/Laborordnung.md'
      - Grundregeln: 'briefings-rules/Grundregeln/index.md'
      - Laser: 'briefings-rules/Einweisung_Laser/index.md'
      - 3D-Drucker: 'briefings-rules/Einweisung_3D-Drucker/index.md'
      - E-Werkstatt: 'briefings-rules/Einweisung_E-Werkstatt/index.md'
      - Elektrowerkzeug: 'briefings-rules/Einweisung_Elektro-Werkzeuge/index.md'
      - Fräsen: 'briefings-rules/Einweisung_Fraese/index.md'

    - Projects:
      - Overview: 'projects.md'
      - Hush-Box: 'projects/Hush-Box.md'
      - Aya: 'projects/Aya.md'
      - Lab-Status: 'projects/Lab-Status.md'
      - Gamebly: 'projects/Gamebly.md'

 #     - Workshops, Talks & Mobile Makerspaces
 #     - FAB101
 #     - ZEIT.RAUM Siegen
 #     - Siegen Unter Tage
 #     - Open Labs & Education (Open Lab, Student Lab, Mobile Labs, HCI Lab, 3D Café, Zukunftspiloten, Holospace, ...)
 #     - YALLAH
 #     - Lab Projects
 #     - (Student) Research
    - Infrastructure:
      - Overview: 'infrastructure/index.md'
      - Room: 'infrastructure/Raum.md'
      - CNC Mills:
        - X-Carve: 'infrastructure/CNC-Fraese_X-Carve.md'
        - Portal mill Heavy: 'infrastructure/CNC-Portalfraese_Heavy.md'
        - Stämpfli: 'infrastructure/Staempfli.md'
      - 3D Printing:
        - 'infrastructure/3D-Druck/Ultimaker.md'
        - 'infrastructure/3D-Druck/PrintrBot.md'
        - 'infrastructure/3D-Druck/Form1.md'
        - 'infrastructure/3D-Druck/LulzBotTAZ5.md'
        - 'infrastructure/3D-Druck/MarkOne.md'
        - 'infrastructure/3D-Druck/MarkTwo.md'
        - 'infrastructure/3D-Druck/Replicator2X.md'
        - 'infrastructure/3D-Druck/ReplicatorDual.md'
        - 'infrastructure/3D-Druck/Aya.md'
      - Electronic Tools: 'infrastructure/Elektrowerkzeug.md'
      - Electronics Area: 'infrastructure/Elektronik-Bereich.md'
      - Laser Cutter: 'infrastructure/Laser-Cutter.md'
      - Warehouse: 'infrastructure/Lager.md'
      - Computer: 'infrastructure/Computer.md'
      
    - Learn & Share:
      - Community & Safety: 'learn-share/community-safety.md'
      - 'How to: Documentation': 'learn-share/how-to-docs.md'
      - Fab Basics: 'learn-share/fab-basics.md'
#      - 'Seminar: Reading Class': 'learn-share/rc.md'
#      - 'Seminar: Open Lab': 'learn-share/openlab-seminar.md'
#      - 'Seminar: LabLab': 'learn-share/lablab.md'
#      - 'Seminar: IoT': 'learn-share/iot.md'
#      - 'Seminar: 3D printing': 'learn-share/3dp.md'
#      - 'Seminar: Produktentwicklung III': 'learn-share/pe3.md'
#      - 'Other learning resources': 'learn-share/other.md'
#      - 'Events': 'events/events.md'
#      - 'Conferences': 'events/conferences.md'
    - Work with us:
      - 'Open Lab Days': 'workwithus/openlabs.md'
      - 'Research': 'workwithus/research.md'
      - 'Consulting': 'workwithus/consulting.md'
      - 'Events': 'workwithus/events.md'
      - 'Qualification': 'workwithus/qualification.md'
    - Imprint: 'imprint.md'


markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
  - footnotes

theme:
  name: material
  custom_dir: 'theme/material'

extra_css:
    - css/footer.css

extra:
  logo: 'images/logo.png'
  palette:
    primary: 'grey'
    accent: 'amber'
  font:
    text: 'Open Sans'
    code: 'Inconsolata'
#  social:
#    - type: 'twitter'
#      link: 'https://twitter.com/fablabsiegen'
#    - type: 'facebook'
#      link: 'http://facebook.com/fablabsiegen'
