site_name: 'Fab Lab Siegen'
repo_url: 'https://github.com/FabLabSiegen/fabdocs'
repo_name: 'Quellcode'
# edit_uri: edit/master/docs/ (change to dev branch?)
site_author: 'Fab Lab Siegen'

nav:
  - Über das Labor:
    - Fab Lab Siegen: 'index.md'
    - Lehre & Bildung: 'lehre.md'
    - Forschung: 'forschung.md'
    - Regionale Rolle: 'region.md'
    - Globales Netzwerk: 'welt.md'    
  
  - Blog:
    - 2019: 
      - blog/2019-07-25-testpost.md
    - 2015:
      - blog/2015-02-22-raum.md  
    - 2014:
      - blog/2014-10-12-makerfaire-dortmund.md
      - blog/2014-07-20-makerfaire-hannover.md
      - blog/2014-06-29-maker-in-palaestina.md
      - blog/2014-06-28-makerprojekte.md
      - blog/2014-06-09-raum-moeglichkeiten.md
      - blog/2014-06-08-ausstattung.md
      - blog/2014-06-07-about.md
      - blog/2014-06-05-rp14.md      
      - blog/2014-06-04-hasi.md
      - blog/2014-06-01-mitmachen.md
      - blog/2014-05-26-stadt.md
      - blog/2014-05-21-printrbot-in-action.md
      - blog/2014-05-15-printrbot.md
      - blog/2014-04-29-kickoff.md
      - blog/2014-04-25-urspruenge.md
      - blog/2014-04-23-esgehtlos.md
    
  - Das Labor nutzen:
    - Infrastruktur im Fab Lab Siegen: 'nutzen/infrastruktur.md'
    - Sicherheits-Einweisungen: 'nutzen/sicherheits-einweisungen.md'
    - Kultur, Kontext & Methoden: 'nutzen/maker-culture.md'
    - Gestaltung in 2D und 3D: 'nutzen/gestaltung.md'
    - Laser-Cutter: 'nutzen/laser.md'
    - 3D-Druck: 'nutzen/3d-druck.md'
    - CNC-Fräsen: 'nutzen/cnc.md'
    - Analoge Elektronik: 'nutzen/analoge-elektronik.md'
    - Mikroelektronik und IoT: 'nutzen/mikro-elektronik.md'
    - Nähen & Wearables: 'nutzen/naehen.md'
#    - Robotik: 'nutzen/robotik.md'

  - Ressourcen:
    - Fotos & Info-Material: 'ressourcen/infos.md'
#   - Handbuch (FAB101)         
    - Mehr über Fab Labs: 'ressourcen/mehr-ueber-fablabs.md'
    - Organisation: 'ressourcen/organisation.md'
    - Laborordnung: 'ressourcen/laborordnung.md'
    - Für Mitarbeiter*Innen: 'ressourcen/intern.md'
    - Dokumentation, Teilen & Website: 'nutzen/dokumentation.md'    
    - Projekte: 
      - Fab Access Control: 'ressourcen/projekte/access-control.md' 
      - Lehrmaterial: 'ressourcen/projekte/lehrmaterial.md'

  - Kontakt:
    - Kontakt: 'kontakt/kontakt.md'
    - Öffnungszeiten: 'kontakt/oeffnungszeiten.md'
    - Kalender: 'kontakt/kalender.md'
    - Unterstützung: 'kontakt/unterstuetzung.md'

theme:
  name: 'material'
  custom_dir: 'theme/'
  feature:
    tabs: true
  palette:
    primary: 'grey'
    accent: 'deep-orange'
  logo: 'images/logo.png'  
  font: false  
  
markdown_extensions:
  - admonition
  - meta
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.mark


extra:
  palette:
    primary: 'grey'
    accent: 'amber'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/fablabsiegen'
    - type: 'facebook'
      link: 'http://facebook.com/fablabsiegen'
    - type: 'image'
      link: 'https://goo.gl/photos/8JjoX3biSTS7AKYw9'

extra_css:
  - css/footer.css

# extra_javascript:
#    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js

# plugins:
#  - bibtex:
#      bib_file: "refs.bib"
#      cite_style: "pandoc"
#  - markdownmermaid    
#  - pdf-export